### ISSUE TITLE
Error since commit 53ccaf3

### ISSUE THREAD

**Issue by ptchamp2016** [seikur0/PGO-mapscan-opt#117]
Hi,
I've been using this map for a few days and all was going good, until I updated it a few minutes ago.

Now I get this output after accounts logins:

```
[+] Starting intelligent scan mode.

[+] Spawn point count: 5001
[+] Type: 1x15, Count: 4414, Percentage: 88.26%
[+] Type: 1x30, Count: 306, Percentage: 6.12%
[+] Type: 1x45, Count: 25, Percentage: 0.5%
[+] Type: 1x60, Count: 1, Percentage: 0.02%
[+] Type: 2x15, Count: 196, Percentage: 3.92%
[+] Type: 1x60h2, Count: 1, Percentage: 0.02%
[+] Type: 1x60h3, Count: 1, Percentage: 0.02%
[+] Type: 1x60h23, Count: 0, Percentage: 0.0%
[+] Type: UNDEF, Count: 57, Percentage: 1.14%

Exception in thread Thread-71:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 832, in run
    if curT <= all_sort[pointnum-1][0]:
IndexError: list index out of range
```

Thanks!

**Comment by seikur0** [comment]
Okay fixed. You should rescan those UNDEF points though, as they are being ignored otherwise.
