### ISSUE TITLE
Failed Pushbullet takes down the entire id

### ISSUE THREAD

**Issue by c00ni** [seikur0/PGO-mapscan-opt#120]
Is it just a matter of putting `pushacc.push_link` in one of those `try:` things? Sorry I don't even Python.
Ideally it'd retry (once, twice, whatever) but it's fine if it'll just keep moving on if that's difficult. It doesn't happen often but having to remote desktop in to restart the entire id and have it catch up again is a drag when you're out hunting.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\mapscanopt\main0.py", line 1265, in run
    pushacc.push_link(notification_text, 'http://www.google.com/maps/place/{},{}'.format(wild
.latitude, wild.longitude))
  File "c:\python27\lib\site-packages\pushbullet\channel.py", line 29, in push_link
    return self._push(data)
  File "c:\python27\lib\site-packages\pushbullet\channel.py", line 36, in _push
    return self._account._push(data)
  File "c:\python27\lib\site-packages\pushbullet\pushbullet.py", line 262, in _push
    r = self._session.post(self.PUSH_URL, data=json.dumps(data))
  File "c:\python27\lib\site-packages\requests\sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "c:\python27\lib\site-packages\requests\adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(10054, 'An existing connection was forcibly cl
osed by the remote host'))
```

**Comment by seikur0** [comment]
At the point of the error, the pushbullet is already sent, so it's just that. Fixed.
