### ISSUE TITLE
IO Error

### ISSUE THREAD

**Issue by FrozenSocket** [seikur0/PGO-mapscan-opt#154]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 1301, in run
    update_data()
  File "main0.py", line 654, in update_data
    cur.execute("INSERT OR REPLACE INTO spawns VALUES(?,?,?,?,?,?,?,?)",[spawnid,round(latitude,5),round(longitude,5),addinfo,pokeid,expiretime,timenow,wID])
OperationalError: disk I/O error

Scan Hangs

**Comment by seikur0** [comment]
Seems like a common issue, I looked it up how to prevent this from happening, read more about it here: http://www.stevemcarthur.co.uk/blog/post/some-kind-of-disk-io-error-occurred-sqlite
