### ISSUE TITLE
[crash]  telegrambot after geolocation commit

### ISSUE THREAD

**Issue by dikkedeur** [seikur0/PGO-mapscan-opt#162]
after latest geolocation commit there is a problem when you have telegrambot

here is the console output

[+] Phase complete: 10.0 %
[+](98) Krabby visible for 344 seconds (1541m NE from you)
[+](86) Seel visible for 1363 seconds (1535m NE from you)
[+](129) Magikarp visible for 866 seconds (1560m NE from you)
[+](19) Rattata visible for 872 seconds (1790m NE from you)
[+](100) Voltorb visible for 171 seconds (1773m NE from you)
[+](81) Magnemite visible for 868 seconds (1045m SE from you)
[+](124) Jynx visible for 859 seconds (2009m SW from you)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 1317, in run
    telebot.sendMessage(chat_id=telegram, text='<b>' + notification_text + '</b>\n' + time_text, parse_mode='HTML', disable_web_page_preview='False', disable_notification='False')
UnboundLocalError: local variable 'notification_text' referenced before assignment

[+] Phase complete: 12.0 %
[+] Phase complete: 14.0 %

it then stops.. or halts.

**Comment by dikkedeur** [comment]
it doesnt crash anymore when you set in the config 

"add_location_name": false,

to true..
dunno why that would crash the telegrambot or the server in general, but for me that fixed it.
