### ISSUE TITLE
Error when running a 'seikur0_spir' type plan

### ISSUE THREAD

**Issue by Pedromanuelsilva** [seikur0/PGO-mapscan-opt#225]
You mistyped your nick in

def get_planid(plan):

currently line 855 of main0.py

Currently
`elif plan['type'] == 'seiur0_spir':`

trying to run a "seikuro_spir" plan raises exception

`
Traceback (most recent call last):
  File "main0.py", line 1801, in <module>
    main()
  File "main0.py", line 1762, in main
    set_locations()
  File "main0.py", line 967, in set_locations
    fname_spawnfile = get_planid(scanplan)
  File "main0.py", line 862, in get_planid
    id = '{}__{}_{}'.format(id,plan['subplan_index'],plan['subplans'])
UnboundLocalError: local variable 'id' referenced before assignment
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 1538, in run
    class webhooker(threading.Thread):
AttributeError: 'NoneType' object has no attribute 'Thread'
`

**Comment by seikur0** [comment]
'seikur0_spir', mind that zero :)

**Comment by Pedromanuelsilva** [comment]
Tou missed the k in the elif

**Comment by seikur0** [comment]
Oh damm, thanks! I fixed it.
