### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by kpma1985** [seikur0/PGO-mapscan-opt#23]
Hallo ich habe folgende Exception, wenn ich den Webserver starte.

Kannst du mir da weiterhelfen?

`Exception happened during processing of request from ('192.168.101.254', 17907)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 704, in finish
    self.wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
## error: [Errno 32] Broken pipe

192.168.101.254 - - [29/Jul/2016 13:44:22] code 501, message Unsupported method ('OPTIONS')
192.168.101.254 - - [29/Jul/2016 13:44:22] "OPTIONS / HTTP/1.0" 501 -
^CTraceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 220, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 216, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 599, in test
    httpd.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 236, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 155, in _eintr_retry
    return func(*args)`

**Comment by seikur0** [comment]
I don't know, does it happen after opening the browser? Which one are you using? Try a different one maybe.

**Comment by kpma1985** [comment]
Hi,

im using safari. I replaced the webserver now. and now its okay

thanks

**Comment by seikur0** [comment]
Okay good.
