### ISSUE TITLE
Telebot - database is locked

### ISSUE THREAD

**Issue by nyxdis** [seikur0/PGO-mapscan-opt#246]
I just got this while running the telebot:

```
Traceback (most recent call last):
  File "telebot.py", line 518, in <module>
    pokes = get_active_pokemon()  
  File "telebot.py", line 463, in get_active_pokemon
    pokes = cur.execute('SELECT spawnid, latitude, longitude, spawntype, pokeid, expiretime FROM spawns WHERE (expiretime > ?) AND (fromtime >= 0)',[timenow])
sqlite3.OperationalError: database is locked
```

Guess it was trying to read while the map was writing and instead of trying again, the bot exited.

**Comment by seikur0** [comment]
I gave the sqlite related code an overhaul, so that should be fixed now.
