### ISSUE TITLE
SQLite objects created in a thread can only be used in that same thread

### ISSUE THREAD

**Issue by nyxdis** [seikur0/PGO-mapscan-opt#250]
Just got this while trying to change my radius:

```
Traceback (most recent call last):
  File "/home/christoph/virtualenvs/pgo-mapscan/local/lib/python2.7/site-packages/telepot/__init__.py", line 738, in collector
    callback(item)
  File "/home/christoph/virtualenvs/pgo-mapscan/local/lib/python2.7/site-packages/telepot/helper.py", line 839, in route
    return fn(msg, *args, **kwargs)
  File "telebot.py", line 451, in on_chat_message
    u_settings = set_settings(u_settings['id'], rad=rad)
  File "telebot.py", line 269, in set_settings
    cursor_telebot = db_telebot.cursor()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 1995616256 and this is thread id 1981568096
```

**Comment by seikur0** [comment]
fixed now same as the unicode stuff
