### ISSUE TITLE
Login issues on startup

### ISSUE THREAD

**Issue by c00ni** [seikur0/PGO-mapscan-opt#262]
I've been getting these when starting workers. Maybe about 3 or 4 when I login 80 workers.
The rest of the workers login fine but it never starts scanning.
Aborting and relaunching resolves this as the threads that errored seem to re-login and the rest use the cached login from just before.

```
Exception in thread Thread-54:
Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 1554, in run
    do_login(self.account)
  File "main0.py", line 574, in do_login
    set_api_endpoint(location, account)
  File "main0.py", line 812, in set_api_endpoint
    cursor_accs.execute("INSERT OR REPLACE INTO accounts VALUES(?,?,?,?,?,?,?)", [account['us
er'], account['access_token'], account['access_expire_timestamp'], account['api_url'], accoun
t['auth_ticket']['expire_timestamp_ms'], account['auth_ticket']['start'], account['auth_ticke
t']['end']])
InterfaceError: Error binding parameter 0 - probably unsupported type.

```

**Comment by Coalado** [comment]
Same for me

**Comment by seikur0** [comment]
This was already fixed in one of the last commits.

**Comment by c00ni** [comment]
I'm running the latest one!

**Comment by Coalado** [comment]
Same for me. I run the latest version, and get exactly the error above

**Comment by seikur0** [comment]
Okay sorry for closing it too fast. I just uploaded a fixed version.
