### ISSUE TITLE
spawnview.py exception when dragging to add to plan

### ISSUE THREAD

**Issue by Bothari** [seikur0/PGO-mapscan-opt#263]
While running spawnview.py (Windows 10, cygwin, Python 2.7), I am trying to add additional S2 regions to an initial region. I place a region, then (as directed by the Wiki page) I click and drag on the central marker to try and add neighbouring regions.

The regions are not added, and the python script throws the following error:

```
[2016-09-28 21:18:09,280] ERROR in app: Exception on /_add_regionplans [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "spawnview.py", line 93, in regionplans
    locations = mapl.cover_region_s2((lat_f,lng_f),(lat_t,lng_t))
AttributeError: 'module' object has no attribute 'cover_region_s2'

```

**Comment by seikur0** [comment]
Fixed.
