### ISSUE TITLE
telebot more unicode problems

### ISSUE THREAD

**Issue by c00ni** [seikur0/PGO-mapscan-opt#282]
When I hit 'Ignored Pokemon' I just get this in console:

```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\telepot\__init__.py", line 738, in collector
    callback(item)
  File "c:\python27\lib\site-packages\telepot\helper.py", line 839, in route
    return fn(msg, *args, **kwargs)
  File "telebot.py", line 200, in on_chat_message
    print_log(u'[t] Text received: {}: "{}"'.format(tmp_nick,text))
  File "telebot.py", line 316, in print_log
    print(log)
  File "c:\python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 51-52: character maps
 to <undefined>
```

**Comment by dikkedeur** [comment]
i dont have problems since i have turned logging off, you might try that.

**Comment by c00ni** [comment]
I turned logging off, I'm still getting it? Or did you mean you #'ed out all the logging lines

**Comment by c00ni** [comment]
Yes, commenting out the log line for messages received does work.

Also http://imgur.com/64Q1s3G
ಠ_ಠ
