### ISSUE TITLE
local variable 'empty_loc' referenced before assignment

### ISSUE THREAD

**Issue by c00ni** [seikur0/PGO-mapscan-opt#95]
So after 2 hours of running both of my instances returned this, each at the end of a run and stopped. What a tease.

```
[+] 0 of 2107 cells detected as empty during last run.
[+] Non-empty heartbeats reached a maximum of 1 retries, allowed: 1.
[+] Average number of retries was 0.0, total number 2.
Exception in thread Thread-78:
Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\mapscanopt\main0.py", line 963, in run
    if empty_loc[l] == runs:  # within whole time came up as empty, standard setting 2 hours
UnboundLocalError: local variable 'empty_loc' referenced before assignment
```

**Comment by Forbes256** [comment]
Ditto. Happened sometime in hour 2. Re-running to monitor.

**Comment by c00ni** [comment]
Now my python ability isn't great (read: non-existant) but I've added empty_loc to line 907 and I think that should fix it.
Will report back in about an hour or two.

**Comment by c00ni** [comment]
I believe that has fixed it as it has been running for well over 2 hours now and I received this at around the 2 hour mark

```
[+] Finished: 100 %

[+] 0 of 2107 cells detected as empty during last run.
[+] Non-empty heartbeats reached a maximum of 0 retries, allowed: 1.
[+] Average number of retries was 0.0, total number 0.
[+] 0 locations were permanently removed as empty. They've been empty during 25 consecutive s
cans covering a time of 7200 seconds.
[+] Scan Time: 305 s
[+] Sleeping for 0 seconds...
```

**Comment by seikur0** [comment]
Fixed in the newest update, sorry for the tease ahaha
